# Generated by Django 5.0.6 on 2024-06-05 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_orderitem_order_alter_orderitem_product'),
        ('order', '0005_order_shipped_date_order_status'),
    ]

    operations = [
    ]
